add_newline = false
command_timeout = 10000

[line_break]
disabled = true

# [aws]
# disabled = true

# [terraform]
# disabled = true

[lua]
disabled = true

# [battery]
# disabled = true

[python]
disabled = true

[rust]
disabled = true

# [c]
# disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[package]
disabled = true

# [cmake]
# disabled = true

[java]
disabled = true

# [gradle]
# disabled = true

# [kotlin]
# disabled = true

# [perl]
# disabled = true

# [os]
# disabled = true

# [dotnet]
# disabled = true

[cmd_duration]
min_time = 200_000

# [git_commit]
# format = ' [\($hash$tag\)]($style)'

[directory]
truncate_to_repo = false
truncation_symbol = '.../'

[git_status]
ahead = '[⇡$count](green)'
behind = '[⇣$count](red)'
conflicted = '[=$count](red)'
deleted = '[✘$count](red)'
diverged = '[⇡⇣$count](red)'
modified = '[!$count](yellow)'
renamed = '[»$count](yellow)'
staged = '[+$count](cyan)'
stashed = '[\$$count](green)'
untracked = '[?$count](cyan)'
